"""Constants for the Daikin Skyport integration."""

from datetime import timedelta

from homeassistant.const import Platform

DOMAIN = "daikinone"
MANUFACTURER = "Daikin"

PLATFORMS = [
    Platform.CLIMATE,
    Platform.SELECT,
    Platform.SENSOR,
]

MIN_TIME_BETWEEN_UPDATES = timedelta(seconds=30)

CONF_OPTION_ENTITY_UID_SCHEMA_VERSION_KEY = "entity_uid_schema_version"
CONF_OPTION_HEAT_PUMP_GROUPS_KEY = "heat_pump_groups"
CONF_OPTION_HEAT_PUMP_GROUPS_SCHEMA_VERSION_KEY = "heat_pump_groups_schema_version"
HEAT_PUMP_GROUPS_SCHEMA_VERSION = 1

CONF_OPTION_EMULATION_TOLERANCE = "emulation_tolerance"
CONF_OPTION_EMULATION_DWELL_MINUTES = "emulation_dwell_minutes"
CONF_OPTION_CONVERT_EXTERNAL_AUTO = "convert_external_auto"
DEFAULT_EMULATION_TOLERANCE = 0.5
DEFAULT_EMULATION_DWELL_MINUTES = 15
DEFAULT_CONVERT_EXTERNAL_AUTO = False

CONF_OPTION_EXTERNAL_TEMPERATURE_CONTROLS = "external_temperature_controls"
DEFAULT_EXTERNAL_TEMPERATURE_MAX_BIAS = 5.0
EXTERNAL_TEMPERATURE_BIAS_STEP = 0.5
EXTERNAL_TEMPERATURE_DEADBAND = 0.3
EXTERNAL_TEMPERATURE_ADJUSTMENT_MINUTES = 15
EXTERNAL_TEMPERATURE_STALE_MINUTES = 30
